version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=password123
      - DJANGO_SU_EMAIL=admin@gmail.com
      - DJANGO_SU_PASSWORD=initial
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123